### ISSUE TITLE
[Improvement] Change the storage format of a .syndicate in S3 Bucket

### ISSUE THREAD

**Issue by bohdan-onsha** [epam/aws-syndicate#179]
Change the storage format of a `.syndicate` file in S3 Bucket from Python Obj to YAML Obj

Current state of the .syndicate file in AWS S3:

```yaml
!!python/object:syndicate.core.project_state.project_state.ProjectState

_dict:

  build_projects_mapping:

    python: src

  events:
```
